import type { AppLocale } from '../i18n/config'

/**
 * Branded per-section Open Graph images (1200×630), generated by scripts/generate-og-images.mjs
 * into public/og/<slug>.<lang>.jpg. Detail pages (portfolio/blog) fall back to their section image.
 */
export const OG_IMAGE_SECTIONS: Record<string, string> = {
  '/': 'home',
  '/packages': 'packages',
  '/portfolio': 'portfolio',
  '/blog': 'blog',
  '/current-projects': 'current-projects',
  '/how-it-works': 'how-it-works',
  '/reviews': 'reviews',
  '/about': 'about',
  '/contact': 'contact',
  '/workshops': 'workshops',
  '/workshops/incompany': 'workshops-incompany',
  '/workshops/1-1': 'workshops-1-1',
  '/ai-talks': 'ai-talks',
  '/privacy': 'privacy',
  '/terms': 'terms',
}

export const OG_IMAGE_WIDTH = 1200
export const OG_IMAGE_HEIGHT = 630

export function ogImageForPath(path: string, locale: AppLocale): string | undefined {
  let slug = OG_IMAGE_SECTIONS[path]
  if (!slug) {
    if (path.startsWith('/portfolio/')) slug = OG_IMAGE_SECTIONS['/portfolio']
    else if (path.startsWith('/blog/')) slug = OG_IMAGE_SECTIONS['/blog']
  }
  if (!slug) return undefined
  return `/og/${slug}.${locale === 'nl-BE' ? 'nl' : 'en'}.jpg`
}
